### ISSUE TITLE
ブロックグループ化に伴う余分なスペースの発生について

### ISSUE THREAD

**Issue by shusei-t** [wctokyo/2023-wctokyo-styles#138]
# 問題点
新デザイン適応後に、複数ブロックをグループ化した時に不要な Padding が入ってしまう。

# 解決策
不要な Padding がどこから発生しているかを確認して、CSS調整をする？

**Comment by shusei-t** [comment]
一旦、暫定的な解決策として
- エディター側で Padding の設定を 0 とする
が見つかりましたので、現状入っているグループブロックかつクリティカルな部分についてはエディター側で再設定をしています。

**Comment by lunaluna** [comment]
```scss
.wp-block-group {
    margin-top: 0;
    padding-top: var(--wp--preset--spacing--60); // これ
    padding-bottom: 0;
}
```
